### ISSUE TITLE
[Feature Request]: Improvements in draft page

### ISSUE THREAD

**Issue by meetbhalodi11** [vishal-kumar3/WriteFlow#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

When user lands on the drafts page, they might to able to comprehend where they should start writing. So improvisation of UX for the same
![Refer the screenshot for suggested improvements](https://github.com/user-attachments/assets/c67a4d05-7c45-4d82-a03d-3639100d813a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by vishal-kumar3** [comment]
Can you also improve the editor info dialog box and it should only appear for the first time only when user created the draft and from then only if user clicks the info button then prompt the dialog box.
![image](https://github.com/user-attachments/assets/f48b6bca-81ab-4e55-b4fc-d9f37ddc66d3)
