### ISSUE TITLE
Adding Contributing.md

### ISSUE THREAD

**Issue by Sibam-Paul** [vishal-kumar3/WriteFlow#3]
Being a Open source Project it's vital to have contributing guidelines to check for over polluting OS source guidelines

Will add all the necessary instructions like 
- How to contribute to the project 
- What are the formats to follow on generating PRs
- etc

@vishal-kumar3 **Please assign me this issue under hacktoberfest so that I can work on it**

**Comment by thezeeshanhassan** [comment]
I'm requesting this issue to be tagged with "hacktoberfest." I believe it would be a great opportunity for me to contribute on this.

**Comment by vishal-kumar3** [comment]
> I'm requesting this issue to be tagged with "hacktoberfest." I believe it would be a great opportunity for me to contribute on this.

Create another issue regarding the project like features/ bugs related to backend or frontend and i will assign it to you.
