### ISSUE TITLE
Implement responsiveness to the settings page.

### ISSUE THREAD

**Issue by vishal-kumar3** [vishal-kumar3/WriteFlow#5]
Make the settings routes/ pages responsive for mobile phones.

**Comment by Neel-07** [comment]
can this issue be assigned to me @vishal-kumar3

**Comment by vishal-kumar3** [comment]
> can this issue be assigned to me @vishal-kumar3

Make a PR request after making changes and if you need anything or have questions then ask me.

**Comment by Neel-07** [comment]
<img width="742" alt="image" src="https://github.com/user-attachments/assets/981f2557-58ac-4edf-a26d-1b31ec1029f1">
@vishal-kumar3 facing an issue while running in localhost, is it  related to .env.local or is the prisma working fine, if you can help me understand the issue it would be really helpful

**Comment by vishal-kumar3** [comment]
yeah you need to have a database url and everything given in the .env.local file...
create a file named .env using terminal ( touch .env [command] ) or using vs code.
If you know docker then run a postgres server docker change the database url, and rest of the field and you are good to go.
Docker Video:- https://www.youtube.com/watch?v=G3gnMSyX-XM&t=214s&pp=ygUTZG9ja2VyIHJ1biBwb3N0Z3Jlcw%3D%3D

**Comment by vishal-kumar3** [comment]
@Neel-07 I have updated the readme.md and .env.local file go through it. and if you face any problem then ask me.

**Comment by vishal-kumar3** [comment]
Hey @Neel-07, are you working on this? can i ask for what progress you did or if you are facing problem setting up development environment.

**Comment by Neel-07** [comment]
Hello @vishal-kumar3 I am working on it, installed bun and other things as necessary, the project structure is taking a bit time, will keep you updated 🙂

**Comment by Neel-07** [comment]
@vishal-kumar3 
![image](https://github.com/user-attachments/assets/a1f7b559-aa45-4fac-aa5b-8000d041dd2c)
if you can help me with these unable to login
